name: 一键构建Debug APK
on:
  workflow_dispatch:

env:
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置JDK17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: 配置Flutter stable通道
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: 升级Flutter到最新
        run: flutter upgrade

      - name: 关闭Flutter Analytics
        run: flutter config --no-analytics

      - name: 清理+安装依赖
        run: |
          flutter clean
          flutter pub get

      - name: 编译Debug APK
        run: flutter build apk --debug

      - name: 提取APK
        run: mkdir output && cp build/app/outputs/flutter-apk/app-debug.apk output/

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-file
          path: output/
          retention-days: 30
